const { Pool } = require('pg');
const pool = new Pool({ connectionString: 'postgresql://genuai_admin:GenuAI2026!db@genuai-db.c1048gqcewlj.ap-south-1.rds.amazonaws.com/genuai_db', ssl: { rejectUnauthorized: false } });

const questions = [
  // SOFTWARE ENGINEER
  { role: "Software Engineer", k_level: 1, marks: 1, question_text: "What does HTML stand for?", option_a: "Hyper Text Markup Language", option_b: "High Tech Modern Language", option_c: "Hyper Transfer Markup Language", option_d: "Home Tool Markup Language", correct_answer: "A", explanation: "HTML is the standard markup language for web pages." },
  { role: "Software Engineer", k_level: 1, marks: 1, question_text: "Which symbol is used for single-line comments in JavaScript?", option_a: "/* */", option_b: "//", option_c: "#", option_d: "--", correct_answer: "B", explanation: "// is used for single-line comments in JavaScript." },
  { role: "Software Engineer", k_level: 2, marks: 2, question_text: "What is the time complexity of binary search?", option_a: "O(n)", option_b: "O(n²)", option_c: "O(log n)", option_d: "O(1)", correct_answer: "C", explanation: "Binary search divides array in half each time = O(log n)." },
  { role: "Software Engineer", k_level: 2, marks: 2, question_text: "Which HTTP method is used to update a resource?", option_a: "GET", option_b: "POST", option_c: "PUT", option_d: "DELETE", correct_answer: "C", explanation: "PUT is used to update an existing resource in REST APIs." },
  { role: "Software Engineer", k_level: 3, marks: 3, question_text: "What is a closure in JavaScript?", option_a: "A function that closes the browser", option_b: "A function that has access to its outer scope even after the outer function returns", option_c: "A method to close database connections", option_d: "A way to end a loop", correct_answer: "B", explanation: "Closures allow functions to access variables from their outer scope." },
  { role: "Software Engineer", k_level: 3, marks: 3, question_text: "Which data structure uses LIFO principle?", option_a: "Queue", option_b: "Array", option_c: "Stack", option_d: "Linked List", correct_answer: "C", explanation: "Stack uses Last In First Out (LIFO) principle." },
  { role: "Software Engineer", k_level: 4, marks: 4, question_text: "What is the difference between process and thread?", option_a: "No difference", option_b: "Process is lightweight, thread is heavy", option_c: "Process has its own memory space, threads share memory within a process", option_d: "Threads are faster than processes in all cases", correct_answer: "C", explanation: "Processes have independent memory; threads share process memory." },
  { role: "Software Engineer", k_level: 4, marks: 4, question_text: "What is CAP theorem in distributed systems?", option_a: "Consistency, Availability, Partition tolerance — only 2 can be guaranteed", option_b: "A security framework", option_c: "A database indexing technique", option_d: "Cache, API, Performance theorem", correct_answer: "A", explanation: "CAP theorem states distributed systems can only guarantee 2 of 3 properties." },
  { role: "Software Engineer", k_level: 5, marks: 5, question_text: "What is the purpose of a deadlock detection algorithm?", option_a: "To prevent deadlocks from occurring", option_b: "To identify when a set of processes are waiting for each other indefinitely", option_c: "To kill all processes", option_d: "To increase CPU speed", correct_answer: "B", explanation: "Deadlock detection identifies circular wait conditions in process scheduling." },

  // FRONTEND DEVELOPER
  { role: "Frontend Developer", k_level: 1, marks: 1, question_text: "Which CSS property changes text color?", option_a: "font-color", option_b: "text-color", option_c: "color", option_d: "text-style", correct_answer: "C", explanation: "The CSS 'color' property sets the text color." },
  { role: "Frontend Developer", k_level: 1, marks: 1, question_text: "What does CSS stand for?", option_a: "Cascading Style Sheets", option_b: "Computer Style Sheets", option_c: "Creative Style System", option_d: "Colorful Style Sheets", correct_answer: "A", explanation: "CSS stands for Cascading Style Sheets." },
  { role: "Frontend Developer", k_level: 2, marks: 2, question_text: "What is the Virtual DOM in React?", option_a: "A real browser DOM", option_b: "A lightweight copy of the real DOM used for efficient updates", option_c: "A CSS framework", option_d: "A database", correct_answer: "B", explanation: "Virtual DOM is a lightweight representation for efficient UI updates." },
  { role: "Frontend Developer", k_level: 2, marks: 2, question_text: "Which hook is used for side effects in React?", option_a: "useState", option_b: "useContext", option_c: "useEffect", option_d: "useRef", correct_answer: "C", explanation: "useEffect handles side effects like API calls and subscriptions." },
  { role: "Frontend Developer", k_level: 3, marks: 3, question_text: "What is CSS specificity?", option_a: "How fast CSS loads", option_b: "A ranking system that determines which CSS rule applies when multiple rules target same element", option_c: "The file size of CSS", option_d: "The number of CSS properties", correct_answer: "B", explanation: "Specificity determines which CSS rule wins when multiple rules conflict." },
  { role: "Frontend Developer", k_level: 3, marks: 3, question_text: "What is the difference between == and === in JavaScript?", option_a: "No difference", option_b: "== checks value only, === checks value and type", option_c: "=== is faster than ==", option_d: "== is for numbers only", correct_answer: "B", explanation: "=== is strict equality checking both value and type." },
  { role: "Frontend Developer", k_level: 4, marks: 4, question_text: "What is code splitting in React?", option_a: "Dividing CSS into multiple files", option_b: "Splitting a team into frontend and backend", option_c: "Loading parts of the application lazily to improve initial load performance", option_d: "Breaking code into functions", correct_answer: "C", explanation: "Code splitting enables lazy loading to improve performance." },
  { role: "Frontend Developer", k_level: 5, marks: 5, question_text: "What is the difference between useMemo and useCallback in React?", option_a: "They are identical", option_b: "useMemo memoizes a computed value, useCallback memoizes a function reference", option_c: "useCallback is deprecated", option_d: "useMemo is only for arrays", correct_answer: "B", explanation: "useMemo caches values; useCallback caches function references to prevent re-renders." },

  // BACKEND DEVELOPER
  { role: "Backend Developer", k_level: 1, marks: 1, question_text: "What is an API?", option_a: "Application Programming Interface", option_b: "Automated Program Integration", option_c: "Application Process Interface", option_d: "Advanced Programming Index", correct_answer: "A", explanation: "API stands for Application Programming Interface." },
  { role: "Backend Developer", k_level: 1, marks: 1, question_text: "Which HTTP status code means success?", option_a: "404", option_b: "500", option_c: "200", option_d: "301", correct_answer: "C", explanation: "HTTP 200 OK means the request was successful." },
  { role: "Backend Developer", k_level: 2, marks: 2, question_text: "What is middleware in Express.js?", option_a: "A database layer", option_b: "Functions that execute during the request-response cycle", option_c: "A frontend framework", option_d: "A caching system", correct_answer: "B", explanation: "Middleware functions process requests between receiving and responding." },
  { role: "Backend Developer", k_level: 2, marks: 2, question_text: "What is the purpose of JWT?", option_a: "To style web pages", option_b: "To securely transmit information between parties as a JSON object", option_c: "To create databases", option_d: "To manage CSS", correct_answer: "B", explanation: "JWT enables secure stateless authentication between client and server." },
  { role: "Backend Developer", k_level: 3, marks: 3, question_text: "What is database indexing?", option_a: "Numbering database rows", option_b: "A data structure that improves speed of data retrieval operations", option_c: "Sorting data alphabetically", option_d: "Deleting duplicate records", correct_answer: "B", explanation: "Indexes speed up queries by allowing faster data lookup." },
  { role: "Backend Developer", k_level: 3, marks: 3, question_text: "What is the N+1 query problem?", option_a: "Running one extra query accidentally", option_b: "Executing N additional queries for N records instead of one optimized query", option_c: "A memory overflow error", option_d: "Adding extra columns to a table", correct_answer: "B", explanation: "N+1 problem causes performance issues by making excessive database queries." },
  { role: "Backend Developer", k_level: 4, marks: 4, question_text: "What is database sharding?", option_a: "Deleting old data", option_b: "Horizontal partitioning of data across multiple database instances", option_c: "Creating database backups", option_d: "Encrypting database columns", correct_answer: "B", explanation: "Sharding distributes data across multiple databases for scalability." },
  { role: "Backend Developer", k_level: 5, marks: 5, question_text: "What is the difference between optimistic and pessimistic locking?", option_a: "No difference", option_b: "Optimistic assumes no conflict and validates at commit; pessimistic locks data immediately", option_c: "Pessimistic locking is faster always", option_d: "Optimistic locking is only for reads", correct_answer: "B", explanation: "Optimistic locking reduces contention; pessimistic prevents conflicts upfront." },

  // AI ENGINEER
  { role: "AI Engineer", k_level: 1, marks: 1, question_text: "What does AI stand for?", option_a: "Automated Input", option_b: "Artificial Intelligence", option_c: "Advanced Integration", option_d: "Analog Interface", correct_answer: "B", explanation: "AI stands for Artificial Intelligence." },
  { role: "AI Engineer", k_level: 1, marks: 1, question_text: "Which Python library is most commonly used for machine learning?", option_a: "Django", option_b: "Flask", option_c: "scikit-learn", option_d: "Pygame", correct_answer: "C", explanation: "scikit-learn is the most popular Python library for machine learning." },
  { role: "AI Engineer", k_level: 2, marks: 2, question_text: "What is overfitting in machine learning?", option_a: "When model performs well on training data but poorly on new data", option_b: "When model is too simple", option_c: "When training takes too long", option_d: "When data is missing", correct_answer: "A", explanation: "Overfitting means the model memorizes training data but fails to generalize." },
  { role: "AI Engineer", k_level: 2, marks: 2, question_text: "What is the purpose of a loss function?", option_a: "To delete bad data", option_b: "To measure how well the model predictions match actual values", option_c: "To increase model speed", option_d: "To visualize data", correct_answer: "B", explanation: "Loss function quantifies prediction error to guide model optimization." },
  { role: "AI Engineer", k_level: 3, marks: 3, question_text: "What is gradient descent?", option_a: "A way to visualize data", option_b: "An optimization algorithm that minimizes loss by adjusting weights", option_c: "A type of neural network", option_d: "A data preprocessing technique", correct_answer: "B", explanation: "Gradient descent iteratively adjusts model parameters to minimize loss." },
  { role: "AI Engineer", k_level: 3, marks: 3, question_text: "What is the difference between supervised and unsupervised learning?", option_a: "No difference", option_b: "Supervised uses labeled data, unsupervised finds patterns in unlabeled data", option_c: "Unsupervised is always better", option_d: "Supervised learning does not use data", correct_answer: "B", explanation: "Supervised learning requires labels; unsupervised discovers hidden patterns." },
  { role: "AI Engineer", k_level: 4, marks: 4, question_text: "What is the attention mechanism in transformers?", option_a: "A way to focus on important parts of input sequence when generating output", option_b: "A memory management technique", option_c: "A type of activation function", option_d: "A regularization method", correct_answer: "A", explanation: "Attention allows models to weigh relevance of different input tokens." },
  { role: "AI Engineer", k_level: 5, marks: 5, question_text: "What is the vanishing gradient problem in deep learning?", option_a: "When gradients become too large during backpropagation", option_b: "When gradients become extremely small causing earlier layers to learn very slowly", option_c: "When the model loses its weights", option_d: "When training data disappears", correct_answer: "B", explanation: "Vanishing gradients prevent deep networks from learning long-range dependencies." },

  // DATA SCIENTIST
  { role: "Data Scientist", k_level: 1, marks: 1, question_text: "What does CSV stand for?", option_a: "Comma Separated Values", option_b: "Computer Stored Values", option_c: "Calculated Statistical Values", option_d: "Common System Variables", correct_answer: "A", explanation: "CSV stands for Comma Separated Values, a common data format." },
  { role: "Data Scientist", k_level: 1, marks: 1, question_text: "Which Python library is used for data manipulation?", option_a: "NumPy", option_b: "Pandas", option_c: "Matplotlib", option_d: "Seaborn", correct_answer: "B", explanation: "Pandas is the primary library for data manipulation and analysis." },
  { role: "Data Scientist", k_level: 2, marks: 2, question_text: "What is a null hypothesis?", option_a: "A hypothesis with no data", option_b: "The default assumption that there is no significant effect or relationship", option_c: "A proven fact", option_d: "A rejected theory", correct_answer: "B", explanation: "Null hypothesis assumes no significant difference or effect exists." },
  { role: "Data Scientist", k_level: 2, marks: 2, question_text: "What is the purpose of normalization in data preprocessing?", option_a: "To delete outliers", option_b: "To scale features to a similar range to prevent one feature dominating", option_c: "To add more data", option_d: "To sort data alphabetically", correct_answer: "B", explanation: "Normalization prevents features with large values from dominating the model." },
  { role: "Data Scientist", k_level: 3, marks: 3, question_text: "What is the difference between correlation and causation?", option_a: "They are the same", option_b: "Correlation shows relationship between variables; causation means one variable directly causes another", option_c: "Causation is stronger than correlation always", option_d: "Correlation proves causation", correct_answer: "B", explanation: "Correlation does not imply causation — confounding variables may exist." },
  { role: "Data Scientist", k_level: 4, marks: 4, question_text: "What is cross-validation?", option_a: "Validating data across different countries", option_b: "A technique to evaluate model performance by splitting data into multiple train/test subsets", option_c: "A database backup method", option_d: "A way to cross-check with another team", correct_answer: "B", explanation: "Cross-validation provides robust model evaluation by testing on multiple data splits." },
  { role: "Data Scientist", k_level: 5, marks: 5, question_text: "What is the curse of dimensionality?", option_a: "Having too many rows in data", option_b: "The phenomenon where data becomes sparse and distances meaningless as dimensions increase", option_c: "A visualization problem", option_d: "When database dimensions are wrong", correct_answer: "B", explanation: "High dimensions make data sparse, making distance-based algorithms ineffective." },

  // DEVOPS ENGINEER
  { role: "DevOps Engineer", k_level: 1, marks: 1, question_text: "What does CI/CD stand for?", option_a: "Continuous Integration / Continuous Deployment", option_b: "Code Integration / Code Deployment", option_c: "Computer Integration / Computer Delivery", option_d: "Continuous Input / Continuous Data", correct_answer: "A", explanation: "CI/CD automates building, testing, and deploying applications." },
  { role: "DevOps Engineer", k_level: 1, marks: 1, question_text: "What is Docker used for?", option_a: "Database management", option_b: "Containerizing applications for consistent deployment", option_c: "Frontend styling", option_d: "Network security", correct_answer: "B", explanation: "Docker packages applications with dependencies into portable containers." },
  { role: "DevOps Engineer", k_level: 2, marks: 2, question_text: "What is the difference between Docker and Kubernetes?", option_a: "They are identical", option_b: "Docker creates containers; Kubernetes orchestrates and manages multiple containers", option_c: "Kubernetes is older than Docker", option_d: "Docker replaces Kubernetes", correct_answer: "B", explanation: "Docker handles individual containers; Kubernetes manages container clusters." },
  { role: "DevOps Engineer", k_level: 3, marks: 3, question_text: "What is Infrastructure as Code (IaC)?", option_a: "Writing code inside servers", option_b: "Managing and provisioning infrastructure through machine-readable configuration files", option_c: "A programming language", option_d: "A database schema approach", correct_answer: "B", explanation: "IaC enables reproducible, version-controlled infrastructure management." },
  { role: "DevOps Engineer", k_level: 4, marks: 4, question_text: "What is blue-green deployment?", option_a: "Deploying to blue and green servers", option_b: "Running two identical production environments and switching traffic between them for zero-downtime releases", option_c: "A color coding system for servers", option_d: "A load balancing technique", correct_answer: "B", explanation: "Blue-green deployment enables zero-downtime releases with instant rollback." },
  { role: "DevOps Engineer", k_level: 5, marks: 5, question_text: "What is the difference between horizontal and vertical scaling?", option_a: "No difference", option_b: "Horizontal adds more machines; vertical adds more resources to existing machine", option_c: "Vertical scaling is always better", option_d: "Horizontal scaling is only for databases", correct_answer: "B", explanation: "Horizontal scaling is more resilient; vertical has hardware limits." },

  // FULL STACK DEVELOPER
  { role: "Full Stack Developer", k_level: 1, marks: 1, question_text: "What is the MEAN stack?", option_a: "MongoDB, Express, Angular, Node.js", option_b: "MySQL, Express, API, Node.js", option_c: "MongoDB, Electron, Angular, Nginx", option_d: "MySQL, Ember, Angular, Node.js", correct_answer: "A", explanation: "MEAN stack consists of MongoDB, Express, Angular, and Node.js." },
  { role: "Full Stack Developer", k_level: 1, marks: 1, question_text: "What does REST stand for?", option_a: "Remote Execution State Transfer", option_b: "Representational State Transfer", option_c: "Rapid Encoding Standard Transfer", option_d: "Remote Standard Transfer", correct_answer: "B", explanation: "REST stands for Representational State Transfer." },
  { role: "Full Stack Developer", k_level: 2, marks: 2, question_text: "What is CORS?", option_a: "A CSS framework", option_b: "Cross-Origin Resource Sharing — controls which domains can access your API", option_c: "A database protocol", option_d: "A JavaScript library", correct_answer: "B", explanation: "CORS controls cross-domain API access for security." },
  { role: "Full Stack Developer", k_level: 3, marks: 3, question_text: "What is the difference between SQL and NoSQL databases?", option_a: "SQL is newer than NoSQL", option_b: "SQL uses structured tables with relations; NoSQL uses flexible document or key-value storage", option_c: "NoSQL is always faster", option_d: "SQL cannot handle large data", correct_answer: "B", explanation: "SQL provides ACID compliance; NoSQL offers flexibility and horizontal scaling." },
  { role: "Full Stack Developer", k_level: 4, marks: 4, question_text: "What is WebSocket and how does it differ from HTTP?", option_a: "They are identical protocols", option_b: "WebSocket provides full-duplex persistent connection; HTTP is request-response stateless", option_c: "HTTP is faster than WebSocket", option_d: "WebSocket only works on mobile", correct_answer: "B", explanation: "WebSockets enable real-time bidirectional communication unlike HTTP." },
  { role: "Full Stack Developer", k_level: 5, marks: 5, question_text: "What is eventual consistency in distributed systems?", option_a: "Data is always consistent immediately", option_b: "System guarantees that given no new updates, all replicas will eventually converge to same value", option_c: "A type of database transaction", option_d: "A caching strategy", correct_answer: "B", explanation: "Eventual consistency trades immediate consistency for availability and partition tolerance." },

  // PRODUCT MANAGER
  { role: "Product Manager", k_level: 1, marks: 1, question_text: "What does KPI stand for?", option_a: "Key Performance Indicator", option_b: "Key Product Integration", option_c: "Knowledge Process Improvement", option_d: "Key Priority Index", correct_answer: "A", explanation: "KPI stands for Key Performance Indicator used to measure success." },
  { role: "Product Manager", k_level: 1, marks: 1, question_text: "What is an MVP in product development?", option_a: "Most Valuable Player", option_b: "Minimum Viable Product", option_c: "Maximum Value Proposition", option_d: "Most Viable Plan", correct_answer: "B", explanation: "MVP is the minimum feature set needed to validate a product idea." },
  { role: "Product Manager", k_level: 2, marks: 2, question_text: "What is the purpose of a product roadmap?", option_a: "A map of the office", option_b: "A strategic plan showing product vision, direction, priorities, and progress over time", option_c: "A technical architecture document", option_d: "A sales presentation", correct_answer: "B", explanation: "Product roadmap aligns stakeholders on product vision and delivery timeline." },
  { role: "Product Manager", k_level: 3, marks: 3, question_text: "What is the RICE scoring framework?", option_a: "Revenue, Income, Cost, Expenditure", option_b: "Reach, Impact, Confidence, Effort — used to prioritize product features", option_c: "Risk, Integration, Complexity, Estimation", option_d: "A food-based management theory", correct_answer: "B", explanation: "RICE helps PMs objectively prioritize features by scoring multiple factors." },
  { role: "Product Manager", k_level: 4, marks: 4, question_text: "What is the difference between output and outcome in product management?", option_a: "They are identical", option_b: "Output is what you build; outcome is the measurable change in user behavior or business metric", option_c: "Outcome is always financial", option_d: "Output is more important than outcome", correct_answer: "B", explanation: "Outcome-driven PM focuses on value delivered, not just features shipped." },
  { role: "Product Manager", k_level: 5, marks: 5, question_text: "What is the Jobs To Be Done (JTBD) framework?", option_a: "A hiring framework", option_b: "A theory that customers hire products to do a specific job — focusing on the underlying motivation rather than demographics", option_c: "A task management system", option_d: "An agile methodology", correct_answer: "B", explanation: "JTBD shifts focus from who the customer is to what they are trying to accomplish." },
];

async function seed() {
  for (const q of questions) {
    await pool.query(
      `INSERT INTO questions (domain, role, k_level, marks, question_text, option_a, option_b, option_c, option_d, correct_answer, difficulty, explanation)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
      [q.role, q.role, q.k_level, q.marks,
       q.question_text, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer,
       q.k_level <= 2 ? 'easy' : q.k_level <= 3 ? 'medium' : 'hard',
       q.explanation]
    );
  }
  console.log(`Seeded ${questions.length} questions!`);
  pool.end();
}
seed().catch(e => { console.log(e.message); pool.end(); });
